/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

public class VentanaPrincipal extends javax.swing.JFrame {
    FondoPanel fondo = new FondoPanel();
    
    public VentanaPrincipal() {
        this.setContentPane(fondo);
        initComponents();
        mostrarPanelPrincipal();
        ocultarPanelInisioSesion();
        ocultarPanelRegistroSesion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new FondoPanel();
        label_titulo1 = new javax.swing.JLabel();
        label_user = new javax.swing.JLabel();
        label_cerrar = new javax.swing.JLabel();
        label_register = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        PanelInicioSesion = new FondoPanel();
        labeltitulo2 = new javax.swing.JLabel();
        panel_inicioSesion = new FondoPanel();
        label_nameuser = new javax.swing.JLabel();
        text_nameuser = new javax.swing.JTextField();
        label_password = new javax.swing.JLabel();
        text_password = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        label_regresar = new javax.swing.JLabel();
        label_igresar = new javax.swing.JLabel();
        panel_UserRegister = new FondoPanel();
        label_registerUser = new javax.swing.JLabel();
        Panel_registerUser = new FondoPanel();
        label_nombre = new javax.swing.JLabel();
        label_passwordR2 = new javax.swing.JLabel();
        text_nameuserR = new javax.swing.JTextField();
        text_nameR = new javax.swing.JTextField();
        label_nameuser2 = new javax.swing.JLabel();
        text_passR2 = new javax.swing.JPasswordField();
        label_passwordR1 = new javax.swing.JLabel();
        text_passR1 = new javax.swing.JPasswordField();
        label_igresar1 = new javax.swing.JLabel();
        label_regresar1 = new javax.swing.JLabel();
        PanelSegundaVentana = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelPrincipal.setBackground(new java.awt.Color(0, 153, 204));
        PanelPrincipal.setPreferredSize(new java.awt.Dimension(820, 450));
        PanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_titulo1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        label_titulo1.setForeground(new java.awt.Color(255, 255, 255));
        label_titulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_titulo1.setText("CUESTIONARIO DE ALGEBRA");
        PanelPrincipal.add(label_titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 650, 90));

        label_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/inicio(1).png"))); // NOI18N
        label_user.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_userMouseClicked(evt);
            }
        });
        PanelPrincipal.add(label_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 240, 240));

        label_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir2.png"))); // NOI18N
        PanelPrincipal.add(label_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, 240, 240));

        label_register.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/register.png"))); // NOI18N
        label_register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_registerMouseClicked(evt);
            }
        });
        PanelPrincipal.add(label_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 240, 240));

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("REGISTRAR USUARIO");
        PanelPrincipal.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, -1, 20));

        jLabel6.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("INICIAR SESION");
        PanelPrincipal.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, -1, -1));

        jLabel7.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("SALIR");
        PanelPrincipal.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 430, -1, -1));

        PanelInicioSesion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labeltitulo2.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        labeltitulo2.setForeground(new java.awt.Color(255, 255, 255));
        labeltitulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labeltitulo2.setText("INICIO SESIÓN");
        PanelInicioSesion.add(labeltitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 510, 80));

        panel_inicioSesion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_nameuser.setForeground(new java.awt.Color(255, 255, 255));
        label_nameuser.setText("NOMBRE DE USUARIO: ");
        panel_inicioSesion.add(label_nameuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 28));

        text_nameuser.setBorder(null);
        text_nameuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_nameuserActionPerformed(evt);
            }
        });
        panel_inicioSesion.add(text_nameuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 340, 30));

        label_password.setForeground(new java.awt.Color(255, 255, 255));
        label_password.setText("CONTRASEÑA:");
        panel_inicioSesion.add(label_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 93, 28));

        text_password.setBorder(null);
        panel_inicioSesion.add(text_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 340, 30));
        panel_inicioSesion.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 340, 10));
        panel_inicioSesion.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 340, 10));

        PanelInicioSesion.add(panel_inicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 450, 260));

        label_regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/restart_back_left_arrow_6022.png"))); // NOI18N
        label_regresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_regresarMouseClicked(evt);
            }
        });
        PanelInicioSesion.add(label_regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 70));

        label_igresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Next_arrow_1559.png"))); // NOI18N
        PanelInicioSesion.add(label_igresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, 70, 80));

        panel_UserRegister.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_registerUser.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        label_registerUser.setForeground(new java.awt.Color(255, 255, 255));
        label_registerUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_registerUser.setText("REGISTRO DE USUARIO");
        panel_UserRegister.add(label_registerUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 510, 50));

        Panel_registerUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_nombre.setForeground(new java.awt.Color(0, 0, 0));
        label_nombre.setText("NOMBRE: ");
        Panel_registerUser.add(label_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 91, 30));

        label_passwordR2.setForeground(new java.awt.Color(0, 0, 0));
        label_passwordR2.setText("NUEVAMENTE LA CONTRASEÑA");
        Panel_registerUser.add(label_passwordR2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 190, 28));

        text_nameuserR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Panel_registerUser.add(text_nameuserR, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 310, 30));

        text_nameR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Panel_registerUser.add(text_nameR, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 310, 30));

        label_nameuser2.setForeground(new java.awt.Color(0, 0, 0));
        label_nameuser2.setText("NOMBRE DE USUARIO: ");
        Panel_registerUser.add(label_nameuser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 28));

        text_passR2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        text_passR2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_passR2ActionPerformed(evt);
            }
        });
        Panel_registerUser.add(text_passR2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 310, 30));

        label_passwordR1.setForeground(new java.awt.Color(0, 0, 0));
        label_passwordR1.setText("CONTRASEÑA:");
        Panel_registerUser.add(label_passwordR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 90, 28));

        text_passR1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        text_passR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_passR1ActionPerformed(evt);
            }
        });
        Panel_registerUser.add(text_passR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 310, 30));

        panel_UserRegister.add(Panel_registerUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 410, 350));

        label_igresar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Next_arrow_1559.png"))); // NOI18N
        panel_UserRegister.add(label_igresar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 460, -1, 70));

        label_regresar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/restart_back_left_arrow_6022.png"))); // NOI18N
        label_regresar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        label_regresar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_regresar1MouseClicked(evt);
            }
        });
        panel_UserRegister.add(label_regresar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 64, 64));

        PanelSegundaVentana.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("jLabel1");
        PanelSegundaVentana.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 140, 140));

        jLabel3.setText("jLabel1");
        PanelSegundaVentana.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 140, 140));

        jLabel4.setText("jLabel1");
        PanelSegundaVentana.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 140, 140, 140));

        jLabel8.setText("jLabel1");
        PanelSegundaVentana.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 140, 140));

        jLabel1.setText("INICIAR TEST");
        PanelSegundaVentana.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 80, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelInicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel_UserRegister, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelSegundaVentana, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelInicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panel_UserRegister, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelSegundaVentana, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_nameuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_nameuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_nameuserActionPerformed

    private void label_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_userMouseClicked
        ocultarPanelPrincipal();
        mostrarPanelInisioSesion();
    }//GEN-LAST:event_label_userMouseClicked

    private void text_passR2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_passR2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_passR2ActionPerformed

    private void label_regresar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_regresar1MouseClicked
        ocultarPanelRegistroSesion();
        mostrarPanelPrincipal();
    }//GEN-LAST:event_label_regresar1MouseClicked

    private void label_regresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_regresarMouseClicked
        ocultarPanelInisioSesion();
        mostrarPanelPrincipal();
    }//GEN-LAST:event_label_regresarMouseClicked

    private void label_registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_registerMouseClicked
        ocultarPanelPrincipal();
        mostrarPanelRegistroSesion();
    }//GEN-LAST:event_label_registerMouseClicked

    private void text_passR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_passR1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_passR1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }
    
    private void mostrarPanelPrincipal(){
        PanelPrincipal.setVisible(true);
        label_titulo1.setVisible(true);
        label_register.setVisible(true);
        label_cerrar.setVisible(true);
        label_user.setVisible(true);
    }
    private void ocultarPanelPrincipal(){
        PanelPrincipal.setVisible(false);
        label_titulo1.setVisible(false);
        label_register.setVisible(false);
        label_cerrar.setVisible(false);
        label_user.setVisible(false);
    }
    private void mostrarPanelInisioSesion(){
        PanelInicioSesion.setVisible(true);
        panel_inicioSesion.setVisible(true);
        label_nameuser.setVisible(true);
        label_password.setVisible(true);
        label_igresar.setVisible(true);
        label_regresar.setVisible(true);
        text_nameuser.setVisible(true);
        text_password.setVisible(true);
        labeltitulo2.setVisible(true);
    }
    
    private void ocultarPanelInisioSesion(){
        PanelInicioSesion.setVisible(false);
        panel_inicioSesion.setVisible(false);
        label_nameuser.setVisible(false);
        label_password.setVisible(false);
        label_igresar.setVisible(false);
        label_regresar.setVisible(false);
        text_nameuser.setVisible(false);
        text_password.setVisible(false);
        labeltitulo2.setVisible(false);
    }
    
    private void mostrarPanelRegistroSesion(){
        Panel_registerUser.setVisible(true);
        panel_UserRegister.setVisible(true);
        label_nameuser2.setVisible(true);
        label_nombre.setVisible(true);
        label_registerUser.setVisible(true);
        label_passwordR2.setVisible(true);
        text_nameR.setVisible(true);
        text_nameuserR.setVisible(true);
        text_passR2.setVisible(true);
        label_igresar1.setVisible(true);
        label_regresar1.setVisible(true);
    }
 
    private void ocultarPanelRegistroSesion(){
        Panel_registerUser.setVisible(false);
        panel_UserRegister.setVisible(false);
        label_nameuser2.setVisible(false);
        label_nombre.setVisible(false);
        label_registerUser.setVisible(false);
        label_passwordR2.setVisible(false);
        text_nameR.setVisible(false);
        text_nameuserR.setVisible(false);
        text_passR2.setVisible(false);
        label_igresar1.setVisible(false);
        label_regresar1.setVisible(false);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelInicioSesion;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JPanel PanelSegundaVentana;
    private javax.swing.JPanel Panel_registerUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel label_cerrar;
    private javax.swing.JLabel label_igresar;
    private javax.swing.JLabel label_igresar1;
    private javax.swing.JLabel label_nameuser;
    private javax.swing.JLabel label_nameuser2;
    private javax.swing.JLabel label_nombre;
    private javax.swing.JLabel label_password;
    private javax.swing.JLabel label_passwordR1;
    private javax.swing.JLabel label_passwordR2;
    private javax.swing.JLabel label_register;
    private javax.swing.JLabel label_registerUser;
    private javax.swing.JLabel label_regresar;
    private javax.swing.JLabel label_regresar1;
    private javax.swing.JLabel label_titulo1;
    private javax.swing.JLabel label_user;
    private javax.swing.JLabel labeltitulo2;
    private javax.swing.JPanel panel_UserRegister;
    private javax.swing.JPanel panel_inicioSesion;
    private javax.swing.JTextField text_nameR;
    private javax.swing.JTextField text_nameuser;
    private javax.swing.JTextField text_nameuserR;
    private javax.swing.JPasswordField text_passR1;
    private javax.swing.JPasswordField text_passR2;
    private javax.swing.JPasswordField text_password;
    // End of variables declaration//GEN-END:variables
}

    class FondoPanel extends JPanel
    {
        private Image imagen;
        
        @Override
        public void paint(Graphics g){
            imagen = new ImageIcon(getClass().getResource("FONDO3.jpeg")).getImage();
            g.drawImage(imagen, 0, 0,getWidth(),getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }